import { PerkDefinitionRecord } from '../database/repositories/perkRepo.js';

export interface PerkMetadata extends PerkDefinitionRecord {
  category:
    | 'Progression'
    | 'Cosmetics'
    | 'Roles & Colors'
    | 'Priority Access'
    | 'Mentorship'
    | 'Resources'
    | 'Privileges'
    | 'Events';
  effectType: string;
  effectValue?: string | number;
}

export const ALL_195_PERKS: PerkMetadata[] = [
  // ==========================================
  // Category 1: Progression & XP Boosters (1-25)
  // ==========================================
  {
    id: 'xp_boost_10',
    name: 'Bronze Spark',
    category: 'Progression',
    description: 'Passive 10% XP boost on all server activities and daily tasks.',
    credit_price: 150,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 604800, // 7 days
    is_active: 1,
    effectType: 'xp_multiplier',
    effectValue: 1.1,
  },
  {
    id: 'xp_boost_25',
    name: 'Silver Surge',
    category: 'Progression',
    description: 'Passive 25% XP boost for 7 days.',
    credit_price: 300,
    level_requirement: 2,
    stock: -1,
    duration_seconds: 604800,
    is_active: 1,
    effectType: 'xp_multiplier',
    effectValue: 1.25,
  },
  {
    id: 'xp_boost_50',
    name: 'Gold Overdrive',
    category: 'Progression',
    description: 'Passive 50% XP boost for 48 hours.',
    credit_price: 500,
    level_requirement: 3,
    stock: -1,
    duration_seconds: 172800,
    is_active: 1,
    effectType: 'xp_multiplier',
    effectValue: 1.5,
  },
  {
    id: 'xp_boost_weekend',
    name: 'Weekend Warrior',
    category: 'Progression',
    description: 'Double XP multiplier during Friday-Saturday.',
    credit_price: 250,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 604800,
    is_active: 1,
    effectType: 'weekend_double_xp',
    effectValue: 2.0,
  },
  {
    id: 'streak_freeze_1',
    name: 'Streak Shield Single',
    category: 'Progression',
    description: 'Prevents daily task streak reset on 1 missed day.',
    credit_price: 100,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 0, // Consumable
    is_active: 1,
    effectType: 'streak_freeze',
    effectValue: 1,
  },
  {
    id: 'streak_freeze_pack',
    name: 'Streak Guardian 3-Pack',
    category: 'Progression',
    description: 'Three automatic daily task streak protections.',
    credit_price: 250,
    level_requirement: 2,
    stock: -1,
    duration_seconds: 0,
    is_active: 1,
    effectType: 'streak_freeze',
    effectValue: 3,
  },
  {
    id: 'quest_bonus_xp',
    name: 'Bounty Hunter',
    category: 'Progression',
    description: '25% extra credits on all completed daily tasks.',
    credit_price: 350,
    level_requirement: 2,
    stock: -1,
    duration_seconds: 1209600, // 14 days
    is_active: 1,
    effectType: 'quest_bonus',
    effectValue: 1.25,
  },
  {
    id: 'xp_boost_voice',
    name: 'Voice Scholar',
    category: 'Progression',
    description: '50% bonus XP for active participation in study/workshop voice channels.',
    credit_price: 200,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 604800,
    is_active: 1,
    effectType: 'voice_xp_bonus',
    effectValue: 1.5,
  },
  {
    id: 'xp_boost_pair',
    name: 'Pair Programmer Aura',
    category: 'Progression',
    description: '15% XP bonus when collaborating in pair sessions.',
    credit_price: 180,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 604800,
    is_active: 1,
    effectType: 'pair_xp_bonus',
    effectValue: 1.15,
  },
  {
    id: 'first_post_bonus',
    name: 'Early Bird XP',
    category: 'Progression',
    description: 'Triple XP on the first message sent each calendar day.',
    credit_price: 220,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 2592000, // 30 days
    is_active: 1,
    effectType: 'early_bird_xp',
    effectValue: 3.0,
  },
  {
    id: 'code_share_bonus',
    name: 'Open Sourcerer',
    category: 'Progression',
    description: 'Double XP when sharing verified open-source code in #showcase.',
    credit_price: 300,
    level_requirement: 2,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'code_share_multiplier',
    effectValue: 2.0,
  },
  {
    id: 'mentor_xp_share',
    name: "Guru's Blessing",
    category: 'Progression',
    description: 'Grant 10% bonus XP to your designated community mentee.',
    credit_price: 400,
    level_requirement: 3,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'mentor_share',
    effectValue: 1.1,
  },
  {
    id: 'xp_mega_boost',
    name: 'Hyperdrive Overclock',
    category: 'Progression',
    description: '100% XP boost for 4 continuous hours (cooldown 7 days).',
    credit_price: 600,
    level_requirement: 4,
    stock: -1,
    duration_seconds: 14400, // 4 hours
    is_active: 1,
    effectType: 'xp_multiplier',
    effectValue: 2.0,
  },
  {
    id: 'streak_recovery',
    name: 'Phoenix Streak Restore',
    category: 'Progression',
    description: 'Restore a broken streak lost within the last 72 hours.',
    credit_price: 450,
    level_requirement: 2,
    stock: -1,
    duration_seconds: 0,
    is_active: 1,
    effectType: 'streak_restore',
    effectValue: 1,
  },
  {
    id: 'challenge_multiplier',
    name: 'Hackathon XP Multiplier',
    category: 'Progression',
    description: 'Double rewards during official server hackathons and jams.',
    credit_price: 350,
    level_requirement: 2,
    stock: -1,
    duration_seconds: 604800,
    is_active: 1,
    effectType: 'hackathon_boost',
    effectValue: 2.0,
  },
  {
    id: 'xp_rollover',
    name: 'Credit Overflow Bank',
    category: 'Progression',
    description: 'Unused daily credit caps roll over to the next day up to 50%.',
    credit_price: 500,
    level_requirement: 3,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'rollover_cap',
    effectValue: 0.5,
  },
  {
    id: 'weekly_xp_vault',
    name: 'Vault Interest Yield',
    category: 'Progression',
    description: 'Earn 5% bonus credits weekly on banked credit balance.',
    credit_price: 700,
    level_requirement: 4,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'interest_yield',
    effectValue: 0.05,
  },
  {
    id: 'xp_boost_review',
    name: 'Peer Reviewer Boon',
    category: 'Progression',
    description: '50 bonus XP each time you review a peer portfolio submission.',
    credit_price: 150,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'review_bonus',
    effectValue: 50,
  },
  {
    id: 'squad_xp_buff',
    name: 'Squad Synergy Aura',
    category: 'Progression',
    description: 'Grant all members of your squad a permanent 5% XP buff.',
    credit_price: 800,
    level_requirement: 3,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'squad_buff',
    effectValue: 1.05,
  },
  {
    id: 'double_daily_xp',
    name: 'Task Overload Pass',
    category: 'Progression',
    description: 'Allows completing an extra daily task per day for bonus rewards.',
    credit_price: 400,
    level_requirement: 2,
    stock: -1,
    duration_seconds: 604800,
    is_active: 1,
    effectType: 'extra_daily_task',
    effectValue: 1,
  },
  {
    id: 'night_owl_xp',
    name: 'Night Owl Bonus',
    category: 'Progression',
    description: '20% bonus XP for tasks and messages submitted between 1 AM and 6 AM.',
    credit_price: 200,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'night_owl_multiplier',
    effectValue: 1.2,
  },
  {
    id: 'streak_milestone_boost',
    name: 'Century Club Honor',
    category: 'Progression',
    description: 'Permanent 5% XP bonus once reaching a 100-day task streak.',
    credit_price: 1000,
    level_requirement: 5,
    stock: -1,
    duration_seconds: 0,
    is_active: 1,
    effectType: 'permanent_xp_boost',
    effectValue: 1.05,
  },
  {
    id: 'xp_insurance',
    name: 'Task Insurance Policy',
    category: 'Progression',
    description: 'Receive half XP even if a daily task submission is partially rejected.',
    credit_price: 250,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 1209600,
    is_active: 1,
    effectType: 'task_insurance',
    effectValue: 0.5,
  },
  {
    id: 'bonus_spin_xp',
    name: 'Lucky Byte Daily Roll',
    category: 'Progression',
    description: 'Daily roll for a chance at 50-500 bonus server credits.',
    credit_price: 300,
    level_requirement: 1,
    stock: -1,
    duration_seconds: 2592000,
    is_active: 1,
    effectType: 'daily_spin',
    effectValue: 50,
  },
  {
    id: 'prestige_multiplier',
    name: "Veteran's Edge",
    category: 'Progression',
    description: 'Permanent 10% prestige multiplier after seasonal leaderboard reset.',
    credit_price: 1500,
    level_requirement: 5,
    stock: -1,
    duration_seconds: 0,
    is_active: 1,
    effectType: 'prestige_boost',
    effectValue: 1.1,
  },

  // ==========================================
  // Category 2: Cosmetic Titles & Badges (26-60)
  // ==========================================
  { id: 'title_code_samurai', name: 'Title: Code Samurai', category: 'Cosmetics', description: 'Equippable profile title displayed on your /profile card.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Code Samurai' },
  { id: 'title_pixel_perfectionist', name: 'Title: Pixel Perfectionist', category: 'Cosmetics', description: 'Equippable title for meticulous UI/UX designers.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Pixel Perfectionist' },
  { id: 'title_bug_hunter', name: 'Title: Bug Hunter', category: 'Cosmetics', description: 'Equippable title celebrating debugging tenacity.', credit_price: 120, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Bug Hunter' },
  { id: 'title_egyptian_pharaoh', name: 'Title: كود فرعوني', category: 'Cosmetics', description: 'Egyptian Arabic authentic title: Code Pharaoh.', credit_price: 150, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'كود فرعوني' },
  { id: 'title_senior_progg_disciple', name: "Title: تلميذ بروج", category: 'Cosmetics', description: "Exclusive badge: Senior Progg's Chosen Disciple.", credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'تلميذ بروج' },
  { id: 'title_stack_overflow_guru', name: 'Title: Stack Overflow Guru', category: 'Cosmetics', description: 'Title for members answering community queries.', credit_price: 150, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Stack Overflow Guru' },
  { id: 'title_fullstack_nomad', name: 'Title: Full-Stack Nomad', category: 'Cosmetics', description: 'Title for versatile freelancers.', credit_price: 150, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Full-Stack Nomad' },
  { id: 'title_css_wizard', name: 'Title: CSS Wizard', category: 'Cosmetics', description: 'Title for designers mastering animations and grid layouts.', credit_price: 150, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'CSS Wizard' },
  { id: 'title_terminal_junkie', name: 'Title: Terminal Junkie', category: 'Cosmetics', description: 'Title for CLI power users.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Terminal Junkie' },
  { id: 'title_docker_captain', name: 'Title: Container Master', category: 'Cosmetics', description: 'Title for DevOps and Docker infrastructure builders.', credit_price: 180, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Container Master' },
  { id: 'title_figma_sorcerer', name: 'Title: Figma Sorcerer', category: 'Cosmetics', description: 'Title for component variant and auto-layout wizards.', credit_price: 180, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Figma Sorcerer' },
  { id: 'title_git_rebaser', name: 'Title: Force Push Survivor', category: 'Cosmetics', description: 'Title celebrating surviving disastrous merge conflicts.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Force Push Survivor' },
  { id: 'title_clean_coder', name: 'Title: Clean Code Fanatic', category: 'Cosmetics', description: 'Title for lovers of SOLID principles and refactoring.', credit_price: 180, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Clean Code Fanatic' },
  { id: 'badge_golden_bracket', name: 'Badge: Golden Curly Bracket', category: 'Cosmetics', description: 'Shining golden bracket icon next to your name on cards.', credit_price: 250, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'golden_bracket' },
  { id: 'badge_neon_pen', name: 'Badge: Neon Stylus', category: 'Cosmetics', description: 'Glowing stylus emblem on designer cards.', credit_price: 250, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'neon_pen' },
  { id: 'badge_verified_pro', name: 'Badge: Verified Artisan', category: 'Cosmetics', description: 'Sparkle verified emblem for approved freelancers.', credit_price: 300, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'verified_pro' },
  { id: 'badge_deal_maker', name: 'Badge: Flawless Trader', category: 'Cosmetics', description: 'Awarded to members completing dispute-free escrow deals.', credit_price: 350, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'flawless_trader' },
  { id: 'badge_hackathon_victor', name: 'Badge: Hackathon Champion', category: 'Cosmetics', description: 'Laurel badge on profile for tournament finalists.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'hackathon_victor' },
  { id: 'badge_pro_mentor', name: 'Badge: Community Beacon', category: 'Cosmetics', description: 'Star emblem honoring active community mentors.', credit_price: 400, level_requirement: 4, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'community_beacon' },
  { id: 'card_theme_cyberpunk', name: 'Theme: Cyberpunk Neon', category: 'Cosmetics', description: 'Dark futuristic cyan/magenta layout for your profile card.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'card_theme', effectValue: 'cyberpunk' },
  { id: 'card_theme_dracula', name: 'Theme: Dracula Dark', category: 'Cosmetics', description: 'Purple-accented dark theme for profile cards.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'card_theme', effectValue: 'dracula' },
  { id: 'card_theme_nordic', name: 'Theme: Nordic Frost', category: 'Cosmetics', description: 'Clean icy minimalist layout for profile cards.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'card_theme', effectValue: 'nordic' },
  { id: 'card_theme_solarized', name: 'Theme: Solarized Desert', category: 'Cosmetics', description: 'Warm Egyptian sunset palette for profile cards.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'card_theme', effectValue: 'solarized' },
  { id: 'card_theme_matrix', name: 'Theme: Digital Rain', category: 'Cosmetics', description: 'Falling green glyph matrix layout for profile cards.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'card_theme', effectValue: 'matrix' },
  { id: 'title_bash_artisan', name: 'Title: Script Maestro', category: 'Cosmetics', description: 'Title for automated pipeline builders.', credit_price: 150, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Script Maestro' },
  { id: 'title_ai_whisperer', name: 'Title: Prompt Engineer', category: 'Cosmetics', description: 'Title celebrating LLM and AI logic integration.', credit_price: 180, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Prompt Engineer' },
  { id: 'title_speed_demon', name: 'Title: Sub-Second Latency', category: 'Cosmetics', description: 'Title for performance and caching optimizers.', credit_price: 200, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Sub-Second Latency' },
  { id: 'title_refactor_king', name: 'Title: Legacy Code Tamer', category: 'Cosmetics', description: 'Title for engineers fearless in legacy codebases.', credit_price: 200, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Legacy Code Tamer' },
  { id: 'badge_coffee_fueled', name: 'Badge: Infinite Caffeine', category: 'Cosmetics', description: 'Coffee mug emblem on user profile card.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'coffee_mug' },
  { id: 'badge_streak_30', name: 'Badge: 30-Day Flame', category: 'Cosmetics', description: 'Fire emblem for achieving a 30-day streak.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'flame_30' },
  { id: 'badge_streak_100', name: 'Badge: Century Blaze', category: 'Cosmetics', description: 'Diamond flame badge for 100 consecutive daily tasks.', credit_price: 600, level_requirement: 4, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'blaze_100' },
  { id: 'badge_streak_365', name: 'Badge: Legendary Solar', category: 'Cosmetics', description: 'Golden sun emblem for 365 daily tasks completed.', credit_price: 1200, level_requirement: 5, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_badge', effectValue: 'solar_365' },
  { id: 'title_algo_master', name: 'Title: O(1) Wizard', category: 'Cosmetics', description: 'Title for algorithm experts.', credit_price: 250, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'O(1) Wizard' },
  { id: 'title_ui_maestro', name: 'Title: Systems Architect', category: 'Cosmetics', description: 'Title for design systems leaders.', credit_price: 250, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Design Systems Architect' },
  { id: 'title_beloved_peer', name: 'Title: Community Favorite', category: 'Cosmetics', description: 'Awarded to members with 100+ peer endorsements.', credit_price: 500, level_requirement: 4, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'profile_title', effectValue: 'Community Favorite' },

  // ==========================================
  // Category 3: Custom Roles & Color Customization (61-85)
  // ==========================================
  { id: 'color_neon_cyan', name: 'Role Color: Electric Cyan', category: 'Roles & Colors', description: 'Vibrant neon cyan username color (#00f0ff).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#00f0ff' },
  { id: 'color_royal_gold', name: 'Role Color: Royal Gold', category: 'Roles & Colors', description: 'Gilded gold username color (#ffd700).', credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#ffd700' },
  { id: 'color_cyber_pink', name: 'Role Color: Synthwave Pink', category: 'Roles & Colors', description: 'Hot synthwave pink username color (#ff007f).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#ff007f' },
  { id: 'color_emerald_green', name: 'Role Color: Terminal Green', category: 'Roles & Colors', description: 'Hacker terminal green username color (#00ff66).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#00ff66' },
  { id: 'color_amethyst_purple', name: 'Role Color: Deep Purple', category: 'Roles & Colors', description: 'Rich amethyst purple username color (#9900ef).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#9900ef' },
  { id: 'color_sunset_orange', name: 'Role Color: Egyptian Sunset', category: 'Roles & Colors', description: 'Warm orange username color (#ff5722).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#ff5722' },
  { id: 'color_crimson_red', name: 'Role Color: Crimson Velvet', category: 'Roles & Colors', description: 'Bold crimson username color (#dc143c).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#dc143c' },
  { id: 'color_matte_black', name: 'Role Color: Stealth Charcoal', category: 'Roles & Colors', description: 'Dark charcoal stealth username color (#222222).', credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#222222' },
  { id: 'color_pure_white', name: 'Role Color: Starlight White', category: 'Roles & Colors', description: 'Clean starlight white username color (#f8f9fa).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#f8f9fa' },
  { id: 'color_pastel_lavender', name: 'Role Color: Pastel Lavender', category: 'Roles & Colors', description: 'Soft lavender username color (#b39ddb).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#b39ddb' },
  { id: 'color_custom_hex', name: 'Custom Hex Color Picker', category: 'Roles & Colors', description: 'Unlock personal color role with any 6-digit hex code.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'custom_hex_role', effectValue: 'custom' },
  { id: 'role_vanity_name', name: 'Vanity Role Name License', category: 'Roles & Colors', description: 'Create a custom personal cosmetic role name on the server.', credit_price: 600, level_requirement: 3, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'vanity_role_name', effectValue: 'custom' },
  { id: 'role_vanity_icon', name: 'Vanity Role Icon License', category: 'Roles & Colors', description: 'Upload a custom mini-icon next to your role in Discord.', credit_price: 700, level_requirement: 4, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'vanity_role_icon', effectValue: 'custom' },
  { id: 'color_gradient_shift', name: 'Gradient Shift Color Role', category: 'Roles & Colors', description: 'Dual-tone gradient mimic designation in member list.', credit_price: 800, level_requirement: 4, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'gradient_role', effectValue: 'gradient' },
  { id: 'color_mint_fresh', name: 'Role Color: Mint Leaf', category: 'Roles & Colors', description: 'Crisp mint green username color (#00e676).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#00e676' },
  { id: 'color_ice_blue', name: 'Role Color: Glacial Azure', category: 'Roles & Colors', description: 'Cool light blue username color (#80d8ff).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#80d8ff' },
  { id: 'color_ruby_glow', name: 'Role Color: Radiant Ruby', category: 'Roles & Colors', description: 'Radiant ruby red username color (#ff1744).', credit_price: 180, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#ff1744' },
  { id: 'color_amber_flame', name: 'Role Color: Warm Amber', category: 'Roles & Colors', description: 'Glowing amber username color (#ffab00).', credit_price: 180, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#ffab00' },
  { id: 'color_midnight_navy', name: 'Role Color: Midnight Navy', category: 'Roles & Colors', description: 'Deep dark blue username color (#1a237e).', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#1a237e' },
  { id: 'role_vip_supporter', name: 'Role: Server Supporter', category: 'Roles & Colors', description: 'Distinguished supporter badge and elevated member list role.', credit_price: 1000, level_requirement: 3, stock: -1, duration_seconds: 7776000, is_active: 1, effectType: 'supporter_role', effectValue: 'vip' },
  { id: 'role_alumni', name: 'Role: Senior Progg Alumni', category: 'Roles & Colors', description: 'Cosmetic veteran tag for senior community contributors.', credit_price: 1500, level_requirement: 5, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'alumni_role', effectValue: 'alumni' },
  { id: 'color_rose_gold', name: 'Role Color: Metallic Rose Gold', category: 'Roles & Colors', description: 'Sophisticated rose gold username color (#b76e79).', credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#b76e79' },
  { id: 'color_titanium', name: 'Role Color: Titanium Gray', category: 'Roles & Colors', description: 'Sleek titanium industrial gray color (#878681).', credit_price: 180, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#878681' },
  { id: 'color_matrix_green', name: 'Role Color: Matrix Glow', category: 'Roles & Colors', description: 'Classic green phosphor matrix shade (#03a062).', credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'role_color', effectValue: '#03a062' },
  { id: 'role_tag_custom', name: 'Custom Name Prefix Tag', category: 'Roles & Colors', description: 'Custom bracket prefix tag displayed before your nickname.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'custom_prefix_tag', effectValue: 'tag' },

  // ==========================================
  // Category 4: Priority Help & Queue Skips (86-110)
  // ==========================================
  { id: 'priority_help_pass', name: 'Fast-Track Help Desk', category: 'Priority Access', description: 'Pumps technical questions to the top of #help triage.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 86400, is_active: 1, effectType: 'priority_queue', effectValue: 'help' },
  { id: 'priority_code_review', name: 'Speed Code Review Pass', category: 'Priority Access', description: 'Guaranteed Senior Progg AI code review in under 60 seconds.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'instant_review', effectValue: 'code' },
  { id: 'priority_design_critique', name: 'Express Design Critique', category: 'Priority Access', description: 'Elevated priority in UI/UX feedback queue.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'instant_review', effectValue: 'design' },
  { id: 'pin_question_slot', name: 'Showcase Pin Ticket', category: 'Priority Access', description: 'Pin your technical question or project for 2 hours in #help.', credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 7200, is_active: 1, effectType: 'pin_message', effectValue: 2 },
  { id: 'fast_middleman_triage', name: 'VIP Escrow Triage', category: 'Priority Access', description: 'Prioritizes deal assignment to senior middleman within 15 mins.', credit_price: 250, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'priority_escrow', effectValue: 15 },
  { id: 'skip_vetting_cooldown', name: 'Fast-Track Retest Pass', category: 'Priority Access', description: 'Waive the 7-day cooldown on retaking a failed skill test.', credit_price: 300, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'cooldown_skip', effectValue: 'retest' },
  { id: 'priority_job_ping', name: 'Job Match Early Alert', category: 'Priority Access', description: 'Receive matching job post alerts 30 minutes before public posting.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'job_early_access', effectValue: 30 },
  { id: 'portfolio_spotlight_pass', name: 'Weekly Gallery Spotlight', category: 'Priority Access', description: 'Feature your portfolio embed on the server main announcement channel.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 604800, is_active: 1, effectType: 'spotlight_pass', effectValue: 'portfolio' },
  { id: 'priority_live_stage', name: 'Live Workshop Front Row', category: 'Priority Access', description: 'Jump to the front of the queue to speak or ask questions on live stage.', credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'stage_priority', effectValue: 'speaker' },
  { id: 'urgent_ticket_bump', name: 'Ticket Escalation Flare', category: 'Priority Access', description: 'Sends high-priority notification to online moderators for active tickets.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'ticket_flare', effectValue: 'urgent' },
  { id: 'priority_mentor_pairing', name: 'Rapid Mentor Matching', category: 'Priority Access', description: 'Top-priority matching for 1-on-1 community mentorship.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'mentor_priority', effectValue: 'match' },
  { id: 'extended_help_thread', name: 'Deep Debug Session Pass', category: 'Priority Access', description: 'Prevents #help thread from auto-archiving for 7 days.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 604800, is_active: 1, effectType: 'thread_lock_open', effectValue: 7 },
  { id: 'proposal_fast_review', name: 'Proposal Coach Fast-Track', category: 'Priority Access', description: 'Get instant proposal critique with 3 detailed revisions.', credit_price: 200, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'proposal_coach_instant', effectValue: 3 },
  { id: 'client_check_priority', name: 'Client Red-Flag Instant Scan', category: 'Priority Access', description: 'Immediate processing of client background and red-flag checks.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'client_check_priority', effectValue: 1 },
  { id: 'dispute_fast_summary', name: 'Express Dispute Briefing', category: 'Priority Access', description: 'Immediate AI timeline synthesis during deal disputes.', credit_price: 250, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'dispute_express_summary', effectValue: 1 },
  { id: 'instant_contract_gen', name: 'Express Invoice Generator', category: 'Priority Access', description: 'Instant PDF contract & invoice rendering.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'instant_pdf_gen', effectValue: 1 },
  { id: 'exclusive_help_voice', name: 'Private Debug Room Ticket', category: 'Priority Access', description: 'Create an ephemeral private voice room for pair debugging.', credit_price: 250, level_requirement: 2, stock: -1, duration_seconds: 7200, is_active: 1, effectType: 'ephemeral_debug_room', effectValue: 2 },
  { id: 'code_diff_analysis', name: 'Deep Diff Architect Pass', category: 'Priority Access', description: 'Upload git patch diffs for deep refactor analysis.', credit_price: 300, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'git_diff_analysis', effectValue: 1 },
  { id: 'design_asset_audit', name: 'Design Asset Export Inspector', category: 'Priority Access', description: 'Automated check for Figma asset resolutions and naming conventions.', credit_price: 150, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'design_asset_audit', effectValue: 1 },
  { id: 'priority_ama_question', name: 'Guaranteed AMA Answer', category: 'Priority Access', description: 'Host answers your question first in scheduled AMAs.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'ama_priority', effectValue: 1 },
  { id: 'live_review_slot', name: 'Live Screen-Share Pass', category: 'Priority Access', description: 'Guaranteed spot in weekly live code review session.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'screen_share_slot', effectValue: 1 },
  { id: 'extended_voice_time', name: 'Voice Timekeeper Immunity', category: 'Priority Access', description: 'Bypasses Pomodoro room auto-disconnect timers.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'pomodoro_bypass', effectValue: 1 },
  { id: 'priority_squad_invite', name: 'Squad Headhunter Banner', category: 'Priority Access', description: 'Featured recruiting banner on the server recruitment board.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 604800, is_active: 1, effectType: 'squad_recruiting_banner', effectValue: 1 },
  { id: 'instant_quiz_retry', name: 'Course Quiz Instant Retake', category: 'Priority Access', description: 'Immediate retry on course module quizzes.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'quiz_retake', effectValue: 1 },
  { id: 'direct_staff_consult', name: 'Staff Office Hours Slot', category: 'Priority Access', description: 'Schedule a direct 15-minute consultation with community leads.', credit_price: 600, level_requirement: 4, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'staff_consult', effectValue: 15 },

  // ==========================================
  // Category 5: Private Review Slots & Mentorship (111-135)
  // ==========================================
  { id: 'private_portfolio_teardown', name: '1-on-1 Portfolio Teardown', category: 'Mentorship', description: 'Full private deep-dive review of your portfolio by senior staff.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'mentorship_session', effectValue: 'portfolio' },
  { id: 'mock_technical_interview', name: 'AI Mock Tech Interview', category: 'Mentorship', description: '45-minute live interview simulation with scored feedback rubric.', credit_price: 450, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'interview_session', effectValue: 'technical' },
  { id: 'mock_behavioral_interview', name: 'Client Negotiation Simulator', category: 'Mentorship', description: 'Tough client roleplay session to practice scope pushback.', credit_price: 400, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'interview_session', effectValue: 'client' },
  { id: 'resume_rewrite_session', name: 'CV & Resume Polish Session', category: 'Mentorship', description: 'AI + human mentor CV transformation into high-converting format.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'cv_review', effectValue: 1 },
  { id: 'github_audit_pass', name: 'GitHub Profile Audit', category: 'Mentorship', description: 'Deep review of repository hygiene, documentation, and commits.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'github_audit', effectValue: 1 },
  { id: 'behance_dribbble_audit', name: 'Design Profile Audit', category: 'Mentorship', description: 'Critique on Behance case studies and visual storytelling.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'design_audit', effectValue: 1 },
  { id: 'architecture_review_slot', name: 'Architecture Consultation', category: 'Mentorship', description: 'Review schema design, caching strategies, and scalability.', credit_price: 600, level_requirement: 4, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'architecture_consult', effectValue: 1 },
  { id: 'pricing_strategy_session', name: 'Freelance Rate Optimization', category: 'Mentorship', description: 'Personalized hourly/project rate review for Egyptian & MENA markets.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'rate_consult', effectValue: 1 },
  { id: 'contract_terms_audit', name: 'Contract Plain-Language Audit', category: 'Mentorship', description: 'Clause-by-clause explanation of client contract risks.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'contract_audit', effectValue: 1 },
  { id: 'mentor_session_month', name: 'Monthly Mentor Check-In', category: 'Mentorship', description: 'Dedicated 30-minute monthly guidance with an assigned mentor.', credit_price: 800, level_requirement: 3, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'monthly_mentor', effectValue: 30 },
  { id: 'career_roadmap_consult', name: '6-Month Skill Roadmap', category: 'Mentorship', description: 'Custom milestone plan with weekly checkpoints and goals.', credit_price: 450, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'roadmap_consult', effectValue: 6 },
  { id: 'pitch_deck_review', name: 'Startup Pitch Deck Critique', category: 'Mentorship', description: 'Design, story, and technical feasibility review of client pitch.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'pitch_review', effectValue: 1 },
  { id: 'linkedin_headline_pass', name: 'LinkedIn Optimization', category: 'Mentorship', description: 'Overhaul your headline, about section, and featured works.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'linkedin_review', effectValue: 1 },
  { id: 'upwork_profile_audit', name: 'Upwork/Fiverr Profile Booster', category: 'Mentorship', description: 'Profile copy and proposal strategy check.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'upwork_review', effectValue: 1 },
  { id: 'arabic_english_trans', name: 'Proposal Translation Pass', category: 'Mentorship', description: 'Translate proposal between Arabic & English with professional polish.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'translation_service', effectValue: 1 },
  { id: 'case_study_doctor', name: 'Case Study Polish', category: 'Mentorship', description: 'Transform raw project deliverable into a compelling case study.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'case_study_doctor', effectValue: 1 },
  { id: 'cold_outreach_coaching', name: 'Cold Outreach Coaching', category: 'Mentorship', description: 'Review client acquisition messaging and response strategies.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'outreach_coaching', effectValue: 1 },
  { id: 'pair_prog_senior_progg', name: 'Pair Coding with Senior Progg', category: 'Mentorship', description: 'Extended interactive coding session with the AI brain.', credit_price: 400, level_requirement: 2, stock: -1, duration_seconds: 3600, is_active: 1, effectType: 'ai_pair_session', effectValue: 60 },
  { id: 'security_vuln_audit', name: 'Codebase Security Check', category: 'Mentorship', description: 'Automated vulnerability scan for OWASP Top 10 flaws.', credit_price: 450, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'security_audit', effectValue: 1 },
  { id: 'ui_accessibility_audit', name: 'WCAG Accessibility Audit', category: 'Mentorship', description: 'Color contrast, screen reader compatibility, and target size check.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'a11y_audit', effectValue: 1 },
  { id: 'performance_profiling', name: 'Core Web Vitals Audit', category: 'Mentorship', description: 'Frontend diagnostic breakdown of LCP, FID, and CLS bottlenecks.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'cwv_audit', effectValue: 1 },
  { id: 'database_query_tuning', name: 'SQL Optimization Review', category: 'Mentorship', description: 'Query plan review and index recommendations for slow queries.', credit_price: 450, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'sql_tuning', effectValue: 1 },
  { id: 'api_design_critique', name: 'REST/GraphQL API Critique', category: 'Mentorship', description: 'Resource naming, payload structure, status code & pagination review.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'api_critique', effectValue: 1 },
  { id: 'junior_to_mid_eval', name: 'Mid Promotion Assessment', category: 'Mentorship', description: 'Fast-track evaluation to upgrade from Junior to Mid developer.', credit_price: 500, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'promotion_eval', effectValue: 'Mid' },
  { id: 'mid_to_senior_eval', name: 'Senior Master Assessment', category: 'Mentorship', description: 'Comprehensive architecture defense to upgrade to Senior level.', credit_price: 800, level_requirement: 4, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'promotion_eval', effectValue: 'Senior' },

  // ==========================================
  // Category 6: Resource Library & Unlocks (136-160)
  // ==========================================
  { id: 'resource_contract_bundle', name: 'Legal Contract Bundle', category: 'Resources', description: 'Standard freelance client agreements in English and Egyptian Arabic.', credit_price: 250, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'contracts_bundle' },
  { id: 'resource_invoice_templates', name: 'Invoice Template Pack', category: 'Resources', description: 'Professional customizable HTML/PDF invoice templates.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'invoice_templates' },
  { id: 'resource_figma_starter_kit', name: 'Figma UI Component Kit', category: 'Resources', description: 'Mobile and web design system with 200+ auto-layout components.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'figma_kit' },
  { id: 'resource_design_pattern_ebook', name: 'System Design Handbook', category: 'Resources', description: 'Comprehensive guide to enterprise backend architecture patterns.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'system_design_ebook' },
  { id: 'resource_freelance_pricing_guide', name: 'MENA Rate Guidebook', category: 'Resources', description: 'Pricing intelligence report for Egyptian & Gulf freelance markets.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'pricing_guide' },
  { id: 'resource_proposal_vault', name: '50 Winning Proposals', category: 'Resources', description: 'Vault of 50 real proposals that won $1k+ contracts.', credit_price: 400, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'proposal_vault' },
  { id: 'resource_clean_code_cheatsheet', name: 'Clean Code Cheatsheet', category: 'Resources', description: 'Quick refactoring guide and SOLID principles summary.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'clean_code_cheatsheet' },
  { id: 'resource_docker_k8s_recipes', name: 'Docker & CI/CD Recipes', category: 'Resources', description: 'Production dockerfiles and GitHub Actions workflow templates.', credit_price: 250, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'docker_recipes' },
  { id: 'resource_seo_checklist', name: 'Freelancer SEO Checklist', category: 'Resources', description: 'Actionable speed, meta, and technical SEO audit checklist.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'seo_checklist' },
  { id: 'resource_scope_creep_defense', name: 'Scope Creep Defense Scripts', category: 'Resources', description: 'Pre-written scripts to handle demanding clients professionally.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'scope_scripts' },
  { id: 'resource_arabic_typography', name: 'Arabic Typography Guide', category: 'Resources', description: 'Font pairings, RTL layout best practices, and web font styling.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'arabic_typography' },
  { id: 'resource_backend_roadmap', name: 'Backend Mastery Guide', category: 'Resources', description: 'Node & Python backend learning path and project blueprints.', credit_price: 250, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'backend_roadmap' },
  { id: 'resource_frontend_roadmap', name: 'Next.js 15 Master Blueprint', category: 'Resources', description: 'Server components, caching, and streaming roadmap.', credit_price: 250, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'nextjs_roadmap' },
  { id: 'resource_uiux_heuristics', name: 'UX Heuristics Deck', category: 'Resources', description: 'Interactive card deck of Nielsen Norman usability rules.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'ux_heuristics' },
  { id: 'resource_interview_questions_500', name: '500 Senior Interview Qs', category: 'Resources', description: 'Curated technical interview questions across frontend, backend, devops.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'interview_500' },
  { id: 'resource_freelance_tax_sheet', name: 'Egypt Tax & Banking Guide', category: 'Resources', description: 'Informational reference on receiving international client payments.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'tax_guide' },
  { id: 'resource_tailwind_cheatsheet', name: 'Tailwind Super-Reference', category: 'Resources', description: 'Searchable CSS flexbox, grid, and animation utility guide.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'tailwind_ref' },
  { id: 'resource_database_migration_kit', name: 'Database Migration Kit', category: 'Resources', description: 'Zero-downtime database migration playbooks and rollback scripts.', credit_price: 300, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'db_migration_kit' },
  { id: 'resource_prompt_eng_pack', name: '100 Developer AI Prompts', category: 'Resources', description: 'Tested high-accuracy coding, refactoring, and test-generation prompts.', credit_price: 250, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'prompts_pack' },
  { id: 'resource_git_disaster_recovery', name: 'Git Disaster Recovery Manual', category: 'Resources', description: 'Rescue detached heads, rebase conflicts, and lost commits.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'git_recovery' },
  { id: 'resource_cold_pitch_templates', name: '20 Cold Pitch Templates', category: 'Resources', description: 'Client acquisition outreach emails targeted by industry.', credit_price: 250, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'cold_pitch_templates' },
  { id: 'resource_app_security_checklist', name: 'Security Pre-Launch Audit', category: 'Resources', description: 'Hardening checklist covering headers, CORS, JWT, rate limiting.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'security_checklist' },
  { id: 'resource_color_palette_vault', name: '150 Accessible Palettes', category: 'Resources', description: 'Accessible color schemes with pre-computed contrast ratios.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'color_palettes' },
  { id: 'resource_client_onboarding_form', name: 'Client Onboarding Brief', category: 'Resources', description: 'Automated brief collection form to prevent project scope creep.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'downloadable_bundle', effectValue: 'client_onboarding_form' },
  { id: 'resource_recorded_masterclass', name: 'VIP Masterclass Archive', category: 'Resources', description: 'Unlock all recorded community masterclasses in #recorded-courses.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'masterclass_unlock', effectValue: 'all' },

  // ==========================================
  // Category 7: Community Privileges & Custom Slots (161-180)
  // ==========================================
  { id: 'slot_custom_emoji', name: 'Custom Server Emoji Slot', category: 'Privileges', description: 'Add 1 personal custom emoji to the server emoji list.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'custom_emoji_slot', effectValue: 1 },
  { id: 'slot_custom_sticker', name: 'Custom Server Sticker Slot', category: 'Privileges', description: 'Add 1 personal server sticker.', credit_price: 400, level_requirement: 2, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'custom_sticker_slot', effectValue: 1 },
  { id: 'slot_custom_sound', name: 'Custom Soundboard Slot', category: 'Privileges', description: 'Add 1 custom sound effect to voice channel soundboard.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'custom_soundboard_slot', effectValue: 1 },
  { id: 'privilege_nickname_change', name: 'Nickname Master License', category: 'Privileges', description: 'Change your server nickname freely without staff assistance.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'nickname_privilege', effectValue: 1 },
  { id: 'privilege_thread_creator', name: 'Private Thread Creator', category: 'Privileges', description: 'Create private discussion threads for your project.', credit_price: 250, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'private_thread_privilege', effectValue: 1 },
  { id: 'privilege_external_emojis', name: 'External Emoji Pass', category: 'Privileges', description: 'Use external emojis and stickers anywhere on the server.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'external_emoji_privilege', effectValue: 1 },
  { id: 'privilege_embed_links', name: 'Rich Link Embed Pass', category: 'Privileges', description: 'Embed rich previews when sharing links in general chat.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'embed_link_privilege', effectValue: 1 },
  { id: 'privilege_attach_files', name: 'High-Limit File Attachments', category: 'Privileges', description: 'Attach files in #showcase without standard slowmode restriction.', credit_price: 200, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'attach_files_privilege', effectValue: 1 },
  { id: 'privilege_voice_stage_speaker', name: 'Stage Speaker Pass', category: 'Privileges', description: 'Speak during live community workshop stage events.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'stage_speaker_privilege', effectValue: 1 },
  { id: 'privilege_channel_topic', name: 'Daily Debate Topic Proposer', category: 'Privileges', description: 'Submit an architectural debate topic featured on server pin.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'suggest_topic', effectValue: 1 },
  { id: 'privilege_poll_creator', name: 'Server Poll Creator', category: 'Privileges', description: 'Create official community voting polls.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'poll_privilege', effectValue: 1 },
  { id: 'privilege_quote_poster', name: 'Daily Quote Curator', category: 'Privileges', description: 'Feature your favorite developer quote on morning broadcast.', credit_price: 100, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'quote_curator', effectValue: 1 },
  { id: 'privilege_custom_command', name: 'Voice Intro Jingle', category: 'Privileges', description: 'Play a custom sound intro when entering voice study rooms.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'voice_jingle', effectValue: 1 },
  { id: 'privilege_hall_of_fame', name: 'Hall of Fame Induction', category: 'Privileges', description: 'Permanent entry in the community Hall of Fame showcase.', credit_price: 1500, level_requirement: 5, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'hall_of_fame_entry', effectValue: 1 },
  { id: 'privilege_create_squad', name: 'Squad Founder License', category: 'Privileges', description: 'Found a custom freelancer squad and recruit teammates.', credit_price: 600, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'squad_founder', effectValue: 1 },
  { id: 'privilege_squad_channel', name: 'Private Squad Channel', category: 'Privileges', description: 'Automated private text channel provisioned for your squad.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'squad_channel_privilege', effectValue: 1 },
  { id: 'privilege_squad_voice', name: 'Private Squad Voice Room', category: 'Privileges', description: 'Automated private voice channel for squad collaboration.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'squad_voice_privilege', effectValue: 1 },
  { id: 'privilege_custom_bot_reaction', name: 'Bot Custom Reaction', category: 'Privileges', description: 'Senior Progg bot reacts with a unique emoji whenever you post a win.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'bot_custom_reaction', effectValue: 'fire' },
  { id: 'privilege_banter_immunity', name: 'Banter Shield', category: 'Privileges', description: 'Senior Progg will never tease or roast you; always 100% formal and respectful.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'banter_immunity', effectValue: 1 },
  { id: 'privilege_banter_roast_me', name: 'Ultra Roast Pass', category: 'Privileges', description: 'Senior Progg unleashes hilarious Egyptian developer roasts on demand.', credit_price: 150, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'ultra_roast_pass', effectValue: 1 },

  // ==========================================
  // Category 8: Event & Tournament Perks (181-195)
  // ==========================================
  { id: 'event_early_hackathon', name: 'Hackathon Early Brief', category: 'Events', description: 'Receive hackathon problem statement 2 hours before general drop.', credit_price: 400, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'hackathon_early_brief', effectValue: 120 },
  { id: 'event_vip_seat', name: 'VIP Workshop Front Row', category: 'Events', description: 'Guaranteed seat in limited-capacity expert technical workshops.', credit_price: 300, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'workshop_vip_seat', effectValue: 1 },
  { id: 'event_team_captain', name: 'Registered Team Captain', category: 'Events', description: 'Officially registered team captain badge with custom tournament banner.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'tournament_captain', effectValue: 1 },
  { id: 'event_judge_vote', name: 'Community Judge Ballot', category: 'Events', description: 'Cast a 2x weighted community ballot in hackathon project judging.', credit_price: 450, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'judge_ballot_2x', effectValue: 2 },
  { id: 'event_custom_jam', name: 'Mini-Jam Co-Host License', category: 'Events', description: 'Propose and co-host an official community mini-jam.', credit_price: 600, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'jam_cohost', effectValue: 1 },
  { id: 'event_showcase_shoutout', name: 'Showcase Broadcast Feature', category: 'Events', description: 'Automated broadcast highlighting your best project to all members.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'showcase_broadcast', effectValue: 1 },
  { id: 'event_ama_host_assistant', name: 'AMA Co-Host Badge', category: 'Events', description: 'Help moderate and curate questions during live expert AMAs.', credit_price: 400, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'ama_cohost', effectValue: 1 },
  { id: 'event_ticket_raffle_2x', name: 'Double Raffle Tickets', category: 'Events', description: 'Double winning probability in seasonal hardware and course raffles.', credit_price: 300, level_requirement: 1, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'raffle_tickets_2x', effectValue: 2 },
  { id: 'event_pair_swap_leader', name: 'Pair Swap Organizer', category: 'Events', description: 'Host and organize official design & code pairing sessions.', credit_price: 350, level_requirement: 2, stock: -1, duration_seconds: 2592000, is_active: 1, effectType: 'pair_organizer', effectValue: 1 },
  { id: 'event_trophy_case', name: 'Digital Trophy Display', category: 'Events', description: 'Display custom achievement trophies on web dashboard profile.', credit_price: 500, level_requirement: 3, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'web_trophy_case', effectValue: 1 },
  { id: 'event_season_pass_gold', name: 'Gold Season Supporter Pass', category: 'Events', description: 'Unlock premium reward track items in current competitive season.', credit_price: 1000, level_requirement: 3, stock: -1, duration_seconds: 5184000, is_active: 1, effectType: 'gold_season_pass', effectValue: 1 },
  { id: 'event_exclusive_swag_roll', name: 'Server Swag Draw Entry', category: 'Events', description: 'Entry ticket into exclusive physical community sticker/mug giveaway.', credit_price: 400, level_requirement: 2, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'swag_draw_ticket', effectValue: 1 },
  { id: 'event_alumni_network', name: 'Alumni Syndicate Channel Access', category: 'Events', description: 'Access to private syndicate room for veteran graduates and founders.', credit_price: 1500, level_requirement: 5, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'alumni_syndicate', effectValue: 1 },
  { id: 'event_founder_circle', name: "Founder's Table Advisory", category: 'Events', description: 'Participate in quarterly server roadmap planning with owners.', credit_price: 2000, level_requirement: 5, stock: -1, duration_seconds: 0, is_active: 1, effectType: 'founders_table', effectValue: 1 },
  { id: 'event_immortal_legend', name: 'Immortal Community Key', category: 'Events', description: 'Permanent lifetime VIP status, vanity color, and all core cosmetic perks.', credit_price: 5000, level_requirement: 5, stock: 10, duration_seconds: 0, is_active: 1, effectType: 'immortal_key', effectValue: 1 },
];
