import { aiOrchestrator } from '../orchestrator.js';
import { createLogger } from '../../utils/logger.js';

const logger = createLogger('PlagiarismDetector');

export interface PlagiarismReport {
  plagiarismScore: number; // 0.0 (unique) to 1.0 (definite plagiarism)
  isFlagged: boolean;
  suspicionSignals: string[];
  reasoning: string;
}

export class PlagiarismDetector {
  private static readonly KNOWN_TEMPLATE_SIGNATURES = [
    'create-react-app template',
    'boilerplate generated by',
    'lorem ipsum dolor sit amet',
    'john doe',
    'theme forest sample license',
    'bootstrap starter template',
    'envato market',
  ];

  public async evaluateSubmission(params: {
    urlOrAsset: string;
    description: string;
    codeSnippet?: string;
  }): Promise<PlagiarismReport> {
    const combined = `${params.description} ${params.codeSnippet || ''} ${params.urlOrAsset}`.toLowerCase();
    const signals: string[] = [];

    // 1. Check for common template strings
    for (const sig of PlagiarismDetector.KNOWN_TEMPLATE_SIGNATURES) {
      if (combined.includes(sig)) {
        signals.push(`contains_generic_template_marker: "${sig}"`);
      }
    }

    // 2. Check for suspicious generic tutorial repos
    if (params.urlOrAsset.includes('todo-app') || params.urlOrAsset.includes('calculator') || params.urlOrAsset.includes('weather-app-tutorial')) {
      signals.push('generic_tutorial_project_name');
    }

    const systemPrompt = `
You are Senior Progg's Plagiarism & Originality Inspector.
Evaluate if this submitted work exhibits signs of plagiarism, borrowed stock assets, or superficial boilerplate presented as custom work.
Description: "${params.description}"
Asset/URL: "${params.urlOrAsset}"
Code Excerpt: "${(params.codeSnippet || '').slice(0, 1000)}"

Signals already detected:
${signals.join('\n')}

Output JSON:
{
  "plagiarismScore": number between 0.0 and 1.0,
  "isFlagged": boolean,
  "suspicionSignals": ["signal1"],
  "reasoning": "Explainable assessment of work authenticity"
}
`.trim();

    try {
      const response = await aiOrchestrator.generateJSON<PlagiarismReport>([
        { role: 'system', content: systemPrompt },
        { role: 'user', content: 'Evaluate project originality.' },
      ]);

      if (response && typeof response.plagiarismScore === 'number') {
        const isFlagged = response.plagiarismScore > 0.6 || signals.length > 1;
        return {
          plagiarismScore: response.plagiarismScore,
          isFlagged,
          suspicionSignals: Array.from(new Set([...signals, ...(response.suspicionSignals || [])])),
          reasoning: response.reasoning || 'Evaluated against public repositories and template signatures.',
        };
      }
    } catch (err) {
      logger.error('Failed AI plagiarism evaluation', err);
    }

    const isFlagged = signals.length > 0;
    return {
      plagiarismScore: isFlagged ? 0.7 : 0.1,
      isFlagged,
      suspicionSignals: signals.length > 0 ? signals : ['no_template_markers_detected'],
      reasoning: isFlagged ? 'Flagged based on boilerplate/template signatures.' : 'Work appears original.',
    };
  }
}

export const plagiarismDetector = new PlagiarismDetector();
